secrets: secrets.yml

templates:
  global:
    pyload:
      api: http://localhost:8008/api
      queue: no
      parse_url: yes
      multiple_hoster: yes
      username: '{{ secrets.pyload.usr }}'
      password: '{{ secrets.pyload.pwd }}'
    regexp:
      reject:
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title} # Filtert mehrteilige Serien, immer nur eine Episode
        - \b3-?D\b: {from: title} # Hab kein 3D TV
        - \btrailer\b: {from: title} # Filtert Trailer die evtl. wie Filme benannt sind
        - \b(COMPLETE)\b: {from: title}
    verify_ssl_certificates: no

  serien-global:
    plugin_priority:
      trakt_lookup: 112
    metainfo_series: yes
    thetvdb_lookup: yes
    trakt_lookup: yes
    serienjunkies:
      language: de
      hoster: ul

  filme-global:
    quality:
      - "<=720p"
    imdb_lookup: yes
    tmdb_lookup: yes
    rottentomatoes_lookup: yes
    proper_movies: yes

tasks:
  # Update our Movieque from Trakt.tv Custom List
  trakt_watchlist:
    disable_builtins: [seen]
    template: no_global
    priority: 1
    trakt_list:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      custom: Filme
    accept_all: yes
    seen: local
    queue_movies:
      quality: any

  # Get all Series from custom Trakt.tv List and output it with setting to series.yml also set the Series beginning
  trakt_set_Series:
    disable_builtins: [seen]
    priority: 2
    template: 
      - no_global
      - serien-global
    plugin_priority:
      set: -254
      if: -255
    inputs:
      - trakt_emit:
          username: '{{ secrets.trakt.usr }}'
          password: '{{ secrets.trakt.pwd }}'
          api_key: '{{ secrets.trakt.api }}'
          position: next
          context: collected
          list: Serien
    # This will set the trakt_rating field on entries - see https://github.com/tarzasai/.flexget/tree/master/plugins
    trakt_ratings_lookup:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
    # These are the default values.
    set:
      quality: "<720p webrip+ xvid+"
      specials: no
      tracking: no
    # overrides:
    if:
      # I just need to rate a show on trakt.tv to switch between hi-res and default quality.
      - trakt_rating == "love":
          set:
            #quality: 720p hdtv
            quality: "720p webrip+ xvid+"
    accept_all: yes
    # Creates the settings file for the series plugin - see https://github.com/tarzasai/.flexget/tree/master/plugins
    create_series_config:
      set_fields:
        - begin
        - quality
        - specials
        - tracking
      filename: '/home/saboti/.flexget/series.yml'
    set_series_begin: yes

  # Look up Custom Yahoo Pipes RSS Feed for Movies in the Moviequeue, add to Takt.tv Library and delete the Movie from the Custom List
  filme:
    template: filme-global
    priority: 3
    regexp:
      reject:
        - S\d+E\d+: {from: title}
        - s\d+e\d+: {from: title}
    movie_queue: yes
    inputs:
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=314566c01e38cdcf1517cc7f3adcdd65&_render=rss # ALL Movies 720p
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    trakt_remove:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: Filme
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'
  
  # Look up Custom Yahoo Pipes RSS Feed for Series in the created series.yml file, add them to Trakt.tv Library
  serien:
    template: serien-global
    priority: 4
    regexp:
      reject_excluding:
        - S\d+E\d+: {from: title}
        - s\d+e\d+: {from: title}
      reject:
        - \bsubbed\b: {from: title} # Filtert Subbed
    include: '/home/saboti/.flexget/series.yml'
    inputs:
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=a3bbd36ffce35009c75ebd974083eb77&_render=rss # Serienjunkies Filtered
      #- rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss # Serienjunkies All
      #- rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=1 # Serienjunkies All Page 1
      #- rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=2 # Serienjunkies All Page 2
      #- rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=3 # Serienjunkies All Page 3
      #- rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=4 # Serienjunkies All Page 4
      #- rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=5 # Serienjunkies All Page 5
      #- rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=6 # Serienjunkies All Page 6
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'
    
  # Search for queued Movies on hdarea with the help of a custom yahoo pipe
  filmsuche:
    priority: 5
    template: filme-global
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - search_rss: http://pipes.yahoo.com/pipes/pipe.run?_id=c78ffc88331f35b954f5499f39ce29e5&_render=rss&search={{search_term}} # HDAREA search
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    trakt_remove:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: Filme
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'

  # Search for the Series from series.yml file on Serienjunkies with the help of a custom yahoo pipe
  seriensuche:
    priority: 6
    template: serien-global
    regexp:
      reject_excluding:
        - S\d+E\d+: {from: title}
        - s\d+e\d+: {from: title}
      reject:
        - \bsubbed\b: {from: title} # Filtert Subbed
    include: '/home/saboti/.flexget/series.yml'
    discover:
      what:
        - emit_series: yes
      from:
        - search_rss: http://pipes.yahoo.com/pipes/pipe.run?SeasonEpisode={{search_term}}&Serie={{search_term}}&_id=9ac44b79ddd8b30ae42a1a9e31cb6e03&_render=rss # Search SJ - German
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'
  
schedules:
  - tasks: '*'
    interval:
      hours: 1
