secrets: secrets.yml

templates:
  global:
    pyload:
      api: http://localhost:8000/api
      queue: no
      parse_url: yes
      hoster:
        - UploadedTo
        - RapidgatorNet
      multiple_hoster: no
      username: '{{ secrets.pyload.usr }}'
      password: '{{ secrets.pyload.pwd }}'
    regexp:
      reject:
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title} # Filtert mehrteilige Serien, immer nur eine Episode
        - \b3-?D\b: {from: title} # Hab kein 3D TV
        - \btrailer\b: {from: title} # Filtert Trailer die evtl. wie Filme benannt sind
        - \b(COMPLETE)\b: {from: title}
    verify_ssl_certificates: no

  serien-global:
    plugin_priority:
      trakt_lookup: 112
    metainfo_series: yes
    thetvdb_lookup: yes
    trakt_lookup: yes
    serienjunkies:
      language: de
      hoster: ul

  filme-global:
    quality:
      - "<=720p"
    imdb_lookup: yes
    tmdb_lookup: yes
    rottentomatoes_lookup: yes
    #seen_movies: loose
    proper_movies: yes

tasks:
  # Update our Movieque from Trakt.tv Custom List
  trakt_watchlist:
    template: no_global
    priority: 1
    trakt_list:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      custom: Filme
    accept_all: yes
    seen: local
    queue_movies:
      quality: any

  # Get all Series from custom Trakt.tv List and output it with setting to series.yml also set the Series beginning
  trakt_set_Series:
    priority: 2
    template: 
      - no_global
      - serien-global
    plugin_priority:
      set: -254
      if: -255
    inputs:
      - trakt_emit:
          username: '{{ secrets.trakt.usr }}'
          password: '{{ secrets.trakt.pwd }}'
          api_key: '{{ secrets.trakt.api }}'
          position: next
          context: collected
          list: Serien
    # This will set the trakt_rating field on entries - see https://github.com/tarzasai/.flexget/tree/master/plugins
    trakt_ratings_lookup:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
    # These are the default values.
    set:
      quality: "<720p webrip+ xvid+"
      specials: no
      tracking: no
    # overrides:
    if:
      # I just need to rate a show on trakt.tv to switch between hi-res and default quality.
      - trakt_rating == "love":
          set:
            #quality: 720p hdtv
            quality: "720p webrip+ xvid+"
    accept_all: yes
    # Creates the settings file for the series plugin - see https://github.com/tarzasai/.flexget/tree/master/plugins
    create_series_config:
      set_fields:
        - begin
        - quality
        - specials
        - tracking
      filename: '/root/.flexget/series.yml'
    set_series_begin: yes

  # Look up Custom Yahoo Pipes RSS Feed for Movies in the Moviequeue, add to Takt.tv Library and delete the Movie from the Custom List
  filme:
    template: filme-global
    priority: 3
    regexp:
      reject:
        - S\d+E\d+: {from: title}
        - s\d+e\d+: {from: title}
    movie_queue: yes
    inputs:
      #- rss: http://cinetopia.ws/feed/
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=f0babccee69c68416394e07050686981&_render=rss # HDAREA 720p
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=314566c01e38cdcf1517cc7f3adcdd65&_render=rss # ALL Movies 720p
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=bb1e5656ec4f4235c56903f14c9ba32e&_render=rss # HDAREA xrel retail 720p
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    trakt_remove:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: Filme
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'
  
  # Look up Custom Yahoo Pipes RSS Feed for Series in the created series.yml file, add them to Trakt.tv Library
  serien:
    template: serien-global
    priority: 4
    regexp:
      reject_excluding:
        - S\d+E\d+: {from: title}
        - s\d+e\d+: {from: title}
      reject:
        - \bsubbed\b: {from: title} # Filtert Subbed
    include: '/root/.flexget/series.yml'
    inputs:
      #- rss: http://cinetopia.ws/feed/
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=a3bbd36ffce35009c75ebd974083eb77&_render=rss # Serienjunkies Filtered
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss # Serienjunkies All
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=1 # Serienjunkies All Page 1
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=2 # Serienjunkies All Page 2
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=3 # Serienjunkies All Page 3
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=4 # Serienjunkies All Page 4
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=5 # Serienjunkies All Page 5
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=6 # Serienjunkies All Page 6
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'
    
  # Search for queued Movies on hdarea with the help of a custom yahoo pipe
  filmsuche:
    priority: 5
    template: filme-global
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - search_rss: http://pipes.yahoo.com/pipes/pipe.run?_id=c78ffc88331f35b954f5499f39ce29e5&_render=rss&search={{search_term}} # HDAREA search
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    trakt_remove:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: Filme
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'

  # Search for the Series from series.yml file on Serienjunkies with the help of a custom yahoo pipe
  seriensuche:
    priority: 6
    template: serien-global
    regexp:
      reject_excluding:
        - S\d+E\d+: {from: title}
        - s\d+e\d+: {from: title}
      reject:
        - \bsubbed\b: {from: title} # Filtert Subbed
    include: '/root/.flexget/series.yml'
    discover:
      what:
        - emit_series: yes
      from:
        - search_rss: http://pipes.yahoo.com/pipes/pipe.run?SeasonEpisode={{search_term}}&Serie={{search_term}}&_id=9ac44b79ddd8b30ae42a1a9e31cb6e03&_render=rss
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'
  
    # This one grabs the pilots.
  premieres:
    priority: 7
    template:
      - serien-global
    inputs:
      #- rss: http://cinetopia.ws/feed/
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss # Serienjunkies All
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=1 # Serienjunkies All Page 1
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=2 # Serienjunkies All Page 2
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=3 # Serienjunkies All Page 3
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=4 # Serienjunkies All Page 4
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=5 # Serienjunkies All Page 5
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=6 # Serienjunkies All Page 6
    plugin_priority:
      if: -252
      # In this task it's ok to override the priority set by tvinfo.
      manipulate: -253
      trakt_add: -254
    seen: local
    require_field:
      - tvdb_id
      - tvdb_genres
      - tvdb_first_air_date
    regexp:
      reject:
        - animation: {from: tvdb_genres}
        - children: {from: tvdb_genres}
        - documentary: {from: tvdb_genres}
        - family: {from: tvdb_genres}
        - game show: {from: tvdb_genres}
        - home and garden: {from: tvdb_genres}
        - musical: {from: tvdb_genres}
        - reality: {from: tvdb_genres}
        - soap: {from: tvdb_genres}
        - special interest: {from: tvdb_genres}
        - talk show: {from: tvdb_genres}
    series_premiere:
      timeframe: 4 hours
      quality: "<720p webrip+ xvid+"
    #if:
    #  - tvdb_first_air_date and tvdb_first_air_date < now - timedelta(days=60): reject
    # We need to remove season and episode numbers, otherwise trakt_add plugin will handle entries as episodes.
    manipulate:
      - series_season:
          remove: yes
      - series_episode:
          remove: yes
    # Add the show to the temporary list on trakt.tv so we'll get subsequent episodes too (in the end if I like it I will move it in the main list).
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: Serien_temp

schedules:
  - tasks: '*'
    interval:
      minutes: 30
