secrets: secrets.yml

templates:
  global:
    pyload:
      api: http://localhost:8000/api
      queue: no
      parse_url: yes
      hoster:
        - UploadedTo
        - RapidgatorNet
      multiple_hoster: no
      username: '{{ secrets.pyload.usr }}'
      password: '{{ secrets.pyload.pwd }}'
    regexp:
      reject:
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title} # Filtert mehrteilige Serien, immer nur eine Episode
        - \b3-?D\b: {from: title} # Hab kein 3D TV
        - \btrailer\b: {from: title} # Filtert Trailer die evtl. wie Filme benannt sind
        - \bsubbed\b: {from: title} # Filtert Subbed
        - \b(COMPLETE)\b: {from: title}
    verify_ssl_certificates: no

  serien-global:
    regexp:
      reject_excluding:
        - S\d+E\d+: {from: title}
        - s\d+e\d+: {from: title}
    thetvdb_lookup: yes
    serienjunkies:
      language: de
      hoster: ul
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt.usr }}'
          password: '{{ secrets.trakt.pwd }}'
          api_key: '{{ secrets.trakt.api }}'
          custom: Serien
          strip_dates: yes
      settings:
        #quality: "<720p webrip+ xvid+"
        quality: "<720p hdtv+"
        tracking: no
        identified_by: ep
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'

  filme-global:
    regexp:
      reject:
        - S\d+E\d+: {from: title}
        - s\d+e\d+: {from: title}
        - \b(S\d{1,2})\b: {from: title}
        - \b(S\d+E\d+)\b: {from: title}
    quality:
      - "<=720p hdtv+"
    imdb_lookup: yes
    seen_movies: loose
    proper_movies: yes
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: library
    trakt_remove:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      list: Filme
    pushover:
      userkey: '{{ secrets.pushover.userkey }}'
      apikey: '{{ secrets.pushover.apikey }}'

tasks:
  trakt_watchlist:
    template: no_global
    priority: 1
    trakt_list:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      custom: Filme
    accept_all: yes
    seen: local
    queue_movies: yes

  trakt_set_series_begin:
    template: no_global
    priority: 2
    trakt_emit:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      api_key: '{{ secrets.trakt.api }}'
      context: collected
      list: Serien
    accept_all: yes
    set_series_begin: yes

  filme:
    template: filme-global
    priority: 2
    movie_queue: yes
    inputs:
      #- rss: http://cinetopia.ws/feed/
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=f0babccee69c68416394e07050686981&_render=rss # HDAREA 720p
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=314566c01e38cdcf1517cc7f3adcdd65&_render=rss # ALL Movies 720p
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=bb1e5656ec4f4235c56903f14c9ba32e&_render=rss # HDAREA xrel retail 720p

  serien:
    template: serien-global
    priority: 3
    inputs:
      #- rss: http://cinetopia.ws/feed/
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=a3bbd36ffce35009c75ebd974083eb77&_render=rss # Serienjunkies Filtered
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss # Serienjunkies All
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=1 # Serienjunkies All Page 2
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=2 # Serienjunkies All Page 3
      - rss: http://pipes.yahoo.com/pipes/pipe.run?_id=60c32e6edfa519fbaf911629c2c9e3b0&_render=rss&page=3 # Serienjunkies All Page 4
    accept_all: no
    
  filmsuche:
    priority: 4
    template: filme-global
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - search_rss: http://pipes.yahoo.com/pipes/pipe.run?_id=c78ffc88331f35b954f5499f39ce29e5&_render=rss&search={{search_term}} # HDAREA search

  seriensuche:
    priority: 5
    template: serien-global
    discover:
      what:
        - emit_series: yes
      from:
        - search_rss: http://pipes.yahoo.com/pipes/pipe.run?SeasonEpisode={{search_term}}&Serie={{search_term}}&_id=9ac44b79ddd8b30ae42a1a9e31cb6e03&_render=rss

schedules:
  - tasks: '*'
    interval:
      minutes: 30
